# Generated by Django 4.0.6 on 2022-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('css', 'CSS'), ('php', 'PHP'), ('cpp', 'C++'), ('cs', 'C#')], max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
